services:
  minio:
    platform: linux/amd64
    image: minio/minio:latest
    container_name: minio_s3
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: server /data --console-address ":9001"
  trino:
    image: trinodb/trino:438
    container_name: trino
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/var:/var/trino
      - ./trino/metastore:/tmp/trino-metastore
    user: "1000:1000"
  superset:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - 8088:8088
    environment:
      SUPERSET_SECRET_KEY: your_secret_key
      SUPERSET_LOAD_EXAMPLES: "no"
    volumes:
      - ./superset:/app/superset_home
    depends_on:
      - trino
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"









  # trino:
  #   image: trinodb/trino:latest
  #   container_name: trino_db
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./trino/etc:/etc/trino
  #     - ./trino/data:/data
  #   command: ["/usr/lib/trino/bin/run-trino"]
  #   depends_on:
  #     - minio
  #   user: "1000:1000"