services:
  minio:
    image: minio/minio:latest
    container_name: minio_s3
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: datalake
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: server /data --console-address ":9001"
  trino:
    image: trinodb/trino:latest
    container_name: trino_db
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/data
    command: ["/usr/lib/trino/bin/run-trino"]
    depends_on:
      - minio
    user: "1000:1000"